name: observe
version: 0.10.0-pre.3
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Observable properties and objects for use in template_binding.
  Template Binding extends HTML and the DOM APIs to support a sensible
  separation between the UI (DOM) of a document or application and its
  underlying data (model). Updates to the model are reflected in the DOM and
  user input into the DOM is immediately assigned to the model.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.9.0 <0.13.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
  smoke: '>=0.1.0-pre.0 <0.2.0'
  source_maps: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
environment:
  sdk: '>=1.2.0 <2.0.0'
