name: template_binding
author: Polymer.dart Team <web-ui-dev@dartlang.org>
description: >
  Extends the capabilities of the HTML Template Element by enabling it to
  create, manage, and remove instances of content bound to data defined in Dart.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  logging: any
  mutation_observer: any
  observe: any
dev_dependencies:
  custom_element: any
  unittest: any
