name: unittest
version: 0.10.1+2
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://api.dartlang.org/docs/pkg/unittest
dependencies:
  matcher: '>=0.10.0 <0.11.0'
  mock: '>=0.10.0 <0.11.0'
  stack_trace: '>=0.9.0 <0.10.0'
