// File generated by SCSS from source file swarm.scss
// Do not edit.

class CSSProperty {
  final String name;
  final String value;

  CSSProperty(this.name, this.value) { }
}

class CSSStylet {
  List<CSSProperty> properties;

  CSSStylet(this.properties) { }
}

class CSS {
  // CSS class selectors:
  static final String HBOX = 'hbox';
  static final String VBOX = 'vbox';
  static final String CENTER = 'center';
  static final String PAGED_CONTENT = 'paged-content';
  static final String FULLPAGE = 'fullpage';
  static final String FLEX_ITEM = 'flex-item';
  static final String FLEX = 'flex';
  static final String CONVEYOR_VIEW = 'conveyor-view';
  static final String CONVEYOR_ITEM = 'conveyor-item';
  static final String CONVEYOR_VIEW_CONTAINER = 'conveyor-view-container';
  static final String PAGED_COLUMN_CONTAINER = 'paged-column-container';
  static final String PAGED_COLUMN = 'paged-column';
  static final String PAGE_NUMBER_LEFT = 'page-number-left';
  static final String PAGE_NUMBER_LABEL = 'page-number-label';
  static final String PAGE_NUMBER_RIGHT = 'page-number-right';
  static final String SM_ITEM = 'sm-item';
  static final String SM_ITEM_BOX = 'sm-item-box';
  static final String SM_ROOT = 'sm-root';
  static final String SM_SLIDER_BOX = 'sm-slider-box';
  static final String SM_TRIANGLE = 'sm-triangle';
  static final String INVISIBLE = 'invisible';
  static final String TOUCH_SCROLLBAR = 'touch-scrollbar';
  static final String TOUCH_SCROLLBAR_VERTICAL = 'touch-scrollbar-vertical';
  static final String TOUCH_SCROLLBAR_HORIZONTAL = 'touch-scrollbar-horizontal';
  static final String FRONT_VIEW = 'front-view';
  static final String BOTTOM_VIEW = 'bottom-view';
  static final String TOP_VIEW = 'top-view';
  static final String QUERY = 'query';
  static final String QUERY_NAME_SHADOW = 'query-name-shadow';
  static final String SECTION_VIEW = 'section-view';
  static final String LOADING_SECTION = 'loading-section';
  static final String STORY_SECTION = 'story-section';
  static final String STORY = 'story';
  static final String SNIPPET = 'snippet';
  static final String STORY_SHADOW = 'story-shadow';
  static final String STORY_VIEW = 'story-view';
  static final String PAGE_NUMBER = 'page-number';
  static final String STORY_CONTENT = 'story-content';
  static final String STORY_IMAGE = 'story-image';
  static final String STORY_TEXT_VIEW = 'story-text-view';
  static final String STORY_TITLE = 'story-title';
  static final String HEADER_VIEW = 'header-view';
  static final String APP_TITLE = 'app-title';
  static final String BACK_ARROW = 'back-arrow';
  static final String CONFIG = 'config';
  static final String REFRESH = 'refresh';
  static final String INFO_BUTTON = 'info-button';
  static final String NEW_WINDOW_BUTTON = 'new-window-button';
  static final String WEB_BACK_BUTTON = 'web-back-button';
  static final String WEB_FORWARD_BUTTON = 'web-forward-button';
  static final String WEB_VIEW_BUTTON = 'web-view-button';
  static final String TEXT_VIEW_BUTTON = 'text-view-button';
  static final String BUTTON = 'button';
  static final String DATA_SOURCE_VIEW = 'data-source-view';
  static final String DIALOG_MODAL = 'dialog-modal';
  static final String DIALOG = 'dialog';
  static final String DIALOG_TITLE_AREA = 'dialog-title-area';
  static final String DIALOG_TITLE = 'dialog-title';
  static final String DIALOG_BODY = 'dialog-body';
  static final String DONE_BUTTON = 'done-button';
  static final String HIDDEN_STORY = 'hidden-story';
  static final String HEADER_BACKGROUND = 'header-background';
  static final String TRANSPARENT = 'transparent';

  // CSS state class selectors:
  static final String SEL = 'sel';
  static final String TITLE = 'title';
  static final String NO_THUMB = 'no-thumb';
  static final String BYLINE = 'byline';
  static final String DATELINE = 'dateline';
  static final String STORY_UNREAD = 'story-unread';
  static final String TEXT = 'text';
  static final String CAPTION = 'caption';
  static final String STORY_HEADER = 'story-header';
  static final String STORY_BYLINE = 'story-byline';
  static final String STORY_DATELINE = 'story-dateline';
  static final String HEADER = 'header';
  static final String SPLASH = 'splash';
  static final String FOOTER = 'footer';
  static final String SPLASHIMG = 'splashImg';
  static final String HIDE_ALL_QUERIES = 'hide-all-queries';

  // CSS stylet instances:
}
