util.openWelcomePage
TypeText escape
util.openFileDialog
WaitFor 2, "file search icon"
if (util.isMacOSX) then
	Click "homedir icon"
	Click "file search icon"
	TypeText "codelab"
	TypeText enter
	Click(Text:"finished",CaseSensitive:"yes")
else if (util.isLinux) then
	Click "file search icon"
	TypeText "io-2013-dart-codelab"
	TypeText return
	TypeText downArrow
	TypeText return
	TypeText downArrow
end if
