Run util's init
if util's isMacOSX then
	Run util's selectMenuItem "Dart Editor", "Preferences"
else if util's isLinux then
	Run util's selectMenuItem "Tools", "Preferences"
else (* windows *)
	Run util's selectMenuItem "Tools", "Preferences"
end if
Click (Text:"Hints",CaseSensitive:"yes",ValidCharacters:"*",IgnoreSpaces:"yes",dpi:94)
Click (Text:"Display Hints",CaseSensitive:"yes",ValidCharacters:"*",IgnoreSpaces:"yes",dpi:94)
Typetext enter
Run util's openWelcomePage
