util.init
if (util.isMacOSX) then
	util.selectMenuItem "Dart Editor", "Preferences"
else if util's isLinux then
	util.selectMenuItem "Tools", "Preferences"
else (* windows *)
	util.selectMenuItem "Tools", "Preferences"
end if
Click (Text:"Hints",CaseSensitive:"yes",ValidCharacters:"*",IgnoreSpaces:"yes",dpi:94)
Click (Text:"Display hints",CaseSensitive:"yes",ValidCharacters:"*",IgnoreSpaces:"yes",dpi:94)
util.newline
util.openWelcomePage
