name: shelf
version: 0.3.0+7
author: Dart Team <misc@dartlang.org>
description: Web Server Middleware for Dart
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.2.0 <2.0.0'
documentation: http://api.dartlang.org/docs/pkg/shelf
dependencies:
  collection: '>=0.9.1 <0.10.0'
  path: '>=1.0.0 <2.0.0'
  stack_trace: '>=0.9.2 <0.10.0'
  string_scanner: '>=0.0.0 <0.1.0'
dev_dependencies:
  hop: '>=0.30.2 <0.31.0'
  hop_docgen: '>=0.1.1 <0.2.0'
  http: '>=0.9.2 <0.11.0'
  scheduled_test: '>=0.10.0 <0.11.0'
  unittest: '>=0.10.0 <0.11.0'
