name: dartiverse_search
description: Simple serverside Dart search-engine aggregater, that makes it possible to search GitHub and StackOverflow for dart-related items. The Demo contains a web-interface for performing searches.
dependencies:
  http_server: any
  http: any
  route: any
  logging: any
