/*
 * Copyright (c) 2013, the Dart project authors.
 * 
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.dart.engine.html.parser;

import com.google.dart.engine.html.ast.HtmlUnit;
import com.google.dart.engine.html.scanner.HtmlScanResult;
import com.google.dart.engine.html.scanner.Token;

/**
 * Instances of {@code HtmlParseResult} hold the result of parsing an HTML file.
 * 
 * @coverage dart.engine.html
 */
public class HtmlParseResult extends HtmlScanResult {

  /**
   * The unit containing the parsed information (not {@code null}).
   */
  private final HtmlUnit unit;

  public HtmlParseResult(long modificationTime, Token token, int[] lineStarts, HtmlUnit unit) {
    super(modificationTime, token, lineStarts);
    this.unit = unit;
  }

  /**
   * Answer the unit generated by parsing the source
   * 
   * @return the unit (not {@code null})
   */
  public HtmlUnit getHtmlUnit() {
    return unit;
  }
}
