name: json_rpc_2
version: 0.0.2
author: Dart Team <misc@dartlang.org>
description: An implementation of the JSON-RPC 2.0 spec.
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/json_rpc_2
dependencies:
  stack_trace: '>=0.9.1 <0.10.0'
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.2.0 <2.0.0"

