Run "open codelab file search"
TypeText downArrow, downArrow
TypeText enter
Wait 10
TypeText rightArrow
Wait 5
TypeText rightArrow(* redundant *)
WaitFor 30, "pubspec lock"
Click "pubspec lock"
TypeText downArrow,downArrow,downArrow,rightArrow
RightClick "index html icon"
Click (Text:"New File",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no")
TypeText "document_item.html", enter
Wait 2
DoubleClick (Text:"for later",CaseSensitive:"yes",IgnoreSpaces:"yes",IgnoreUnderscores:"yes",dpi:94)
TypeText downArrow,enter
TypeText commandKey,a
TypeText commandKey,c
TypeText commandKey,w
TypeText commandKey,a
TypeText commandKey,v
TypeText upArrow,upArrow,upArrow
Wait 1
TypeText {{
<element name="x-document-item" constructor="DocumentItem" extends="div" apply-author-styles>
<!-- STEP 2: Define the DOM template for our custom element
}}
TypeText commandKey,rightArrow
TypeText enter
TypeText {{
<template>
</
<!-- STEP 2: Add the script tag that defines this component's behaviour.
}}
TypeText commandKey,rightArrow
TypeText enter
TypeText {{
<script type="application/dart">
}}
TypeText enter,commandKey,rightArrow
TypeText enter
TypeText "</"
Wait 1
Click (Text:"<template",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no")
TypeText rightArrow,rightArrow,rightArrow,rightArrow,rightArrow,rightArrow
TypeText enter
Wait 1
TypeText {{
<!-- STEP 3: On click, select the document.
}}
TypeText commandKey,rightArrow
TypeText enter
TypeText {{
<div class="item {{isActiveClass}}">
}}
TypeText enter,leftArrow,enter
TypeText {{
<div class="title">{{title}}
}}
TypeText commandKey,rightArrow
TypeText enter
TypeText {{
<div class="modified">{{modified}}
}}
TypeText commandKey,rightArrow
TypeText enter
TypeText {{
<!-- STEP 3: Add delete button.
}}
WaitFor 10,(Text:"script type",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no")
Wait 10 (* Puzzle: why is this needed? *)
DoubleClick (Text:"script type",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no")
Wait 2
TypeText commandKey,rightArrow
TypeText enter
Wait 1
TypeText {{
import 'package:web_ui/web_ui.dart';
import 'package:writer/document.dart';
import 'app.dart' as app;
/**

}}
TypeText "This Dart class defines the behavior and",enter
TypeText "* state of the custom element."
TypeText downArrow,enter
TypeText backspace(* should not be needed *)
TypeText {{
class DocumentItem extends WebComponent {
Document doc;

String get title => doc.title.isEmpty ? 'Untitled' : doc.title;

String get modified => dateFormat.format(doc.modified);

String get isActiveClass => doc == app.activeDocument ? 'active' : '';
}}
Wait 1
Click(Text:"Source",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no",dpi:94)
Click(Text:"Format",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no",dpi:94)
Wait 1
TypeText commandKey,s
Wait 5
DoubleClick (Text:"index.html")
TypeText commandKey,f
TypeText "component"
TypeText escape
TypeText downArrow, tab
Wait 1
TypeText {{
<link rel="import" href="document_item.html">
}}
Wait 5
TypeText commandKey,f
TypeText "sidebar"
TypeText escape
TypeText downArrow
Wait 1
TypeText {{
<section id="sidebar" class="{{sidebarClass}}">
}}
TypeText enter,leftArrow,enter
TypeText {{
<div class="toolbar">
}}
TypeText enter,leftArrow,enter
TypeText {{
<!-- STEP 3: Add a button to create a new document.
}}
TypeText commandKey,rightArrow,enter
TypeText {{
<div class="input-wrap">
}}
TypeText enter,leftArrow,enter
TypeText {{
<!-- STEP 4: Add a input box to filter documents.
}}
TypeText downArrow,downArrow,enter
TypeText {{
<!-- Documents list
}}
TypeText commandKey,rightArrow,enter
TypeText {{
<div class="items">
}}
TypeText enter,leftArrow,enter
Wait 1
TypeText {{
<!-- STEP 3: Iterate over list of documents.
}}
TypeText commandKey,rightArrow,enter
TypeText {{
<!-- STEP 2: Add the active document to the sidebar.
}}
TypeText commandKey,rightArrow,enter
TypeText {{
<x-document-item doc="{{activeDocument}}">
}}
TypeText "</"
TypeText downArrow,return
TypeText {{
<!-- Also check out dartlang.org! 
}}
TypeText commandKey,rightArrow,enter
TypeText {{
<div class="footer">
}}
TypeText enter,leftArrow,enter
TypeText {{
<a href="https://github.com/dart-lang/io-2013-dart-codelab">View Source
}}
Wait 1
Click(Text:"Source",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no",dpi:94)
Click(Text:"Format",CaseSensitive:"yes",IgnoreSpaces:"no",IgnoreUnderscores:"no",dpi:94)
Wait 1
TypeText commandKey,s
Wait 30 (* Puzzle: why is analysis so slow? *)
Click "run button"
WaitFor 10,"browser right arrow button"
WaitFor 10, "red stripe"
Click (Text:"Chromium",CaseSensitive:"yes")
Click (Text:"Quit Chromium",CaseSensitive:"yes")
RightClick (Text:"2013",CaseSensitive:"yes",dpi:94)
Click (Text:"Close Folder")
