name: analyzer
version: 0.24.0-dev.2
author: Dart Team <misc@dartlang.org>
description: Static analyzer for Dart.
homepage: http://www.dartlang.org
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.12.1 <0.13.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
  watcher: '>=0.9.0 <0.10.0'
dev_dependencies:
  typed_mock: '>=0.0.4 <1.0.0'
  unittest: '>=0.9.0 <0.12.0'
