name: analyzer
version: 0.25.0+1
author: Dart Team <misc@dartlang.org>
description: Static analyzer for Dart.
homepage: http://www.dartlang.org
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  path: '>=0.9.0 <2.0.0'
  plugin: '<0.2.0'
  watcher: '>=0.9.0 <0.10.0'
dev_dependencies:
  typed_mock: '>=0.0.4 <1.0.0'
  unittest: '>=0.9.0 <0.12.0'
