name: csslib
version: 0.9.2+1
author: Polymer.dart Team <web-ui-dev@dartlang.org>
description: A library for parsing CSS.
homepage: https://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.11.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
  source_maps: '>=0.9.0 <0.10.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
