DoubleClick(Text:"sample.dart") (* activate editor *)
Wait 2
DoubleClick(Text:"import")
util.selectAll
RightClick (500,500)
WaitFor 10, (Text:"Quick Fix",CaseSensitive:"yes",ValidCharacters:"*",IgnoreSpaces:"no",dpi:94)
Click (450,450)
DoubleClick(Text:"import")
TypeText leftArrow (* now at top of file *)
TypeText "library lib;" (* define library and part *)
util.newline
TypeText downArrow
TypeText "part 'other.dart';"
util.newline
util.saveFile
