name: async
version: 1.1.0
author: Dart Team <misc@dartlang.org>
description: Utility functions and classes related to the 'dart:async' library.
homepage: http://www.dartlang.org
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
